package com.easytier.android.ui.theme

import androidx.compose.ui.graphics.Color

// ---- 浅色（取自 Stitch 设计稿 tailwind tokens，5 屏一致）----
val Primary = Color(0xFF0056C5)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF0F6DF3)
val OnPrimaryContainer = Color(0xFFFEFCFF)
val Secondary = Color(0xFF2D4ADD)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFF4B65F7)
val OnSecondaryContainer = Color(0xFFFFFBFF)
val Tertiary = Color(0xFF006290)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF007BB4)
val OnTertiaryContainer = Color(0xFFFCFCFF)
val ErrorC = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
val Surface = Color(0xFFF8F9FA)
val OnSurface = Color(0xFF191C1D)
val SurfaceVariant = Color(0xFFE1E3E4)
val OnSurfaceVariant = Color(0xFF424655)
val SurfaceDim = Color(0xFFD9DADB)
val SurfaceBright = Color(0xFFF8F9FA)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF3F4F5)
val SurfaceContainer = Color(0xFFEDEEEF)
val SurfaceContainerHigh = Color(0xFFE7E8E9)
val SurfaceContainerHighest = Color(0xFFE1E3E4)
val Outline = Color(0xFF727786)
val OutlineVariant = Color(0xFFC2C6D7)
val InverseSurface = Color(0xFF2E3132)
val InverseOnSurface = Color(0xFFF0F1F2)
val InversePrimary = Color(0xFFB0C6FF)
val Background = Color(0xFFF8F9FA)
val OnBackground = Color(0xFF191C1D)
val PrimaryFixed = Color(0xFFD9E2FF)
val PrimaryFixedDim = Color(0xFFB0C6FF)
val OnPrimaryFixed = Color(0xFF001945)
val OnPrimaryFixedVariant = Color(0xFF00429B)
val SecondaryFixed = Color(0xFFDEE0FF)
val SecondaryFixedDim = Color(0xFFBAC3FF)
val OnSecondaryFixed = Color(0xFF000F5C)
val OnSecondaryFixedVariant = Color(0xFF052FC8)
val TertiaryFixed = Color(0xFFCAE6FF)
val TertiaryFixedDim = Color(0xFF8DCDFF)
val OnTertiaryFixed = Color(0xFF001E30)
val OnTertiaryFixedVariant = Color(0xFF004B70)

// ---- 深色（MD3 规则从 fixed 色派生）----
val PrimaryDark = Color(0xFFB0C6FF)
val OnPrimaryDark = Color(0xFF002E6B)
val PrimaryContainerDark = Color(0xFF00429B)
val OnPrimaryContainerDark = Color(0xFFD9E2FF)
val SecondaryDark = Color(0xFFBAC3FF)
val OnSecondaryDark = Color(0xFF0D2193)
val SecondaryContainerDark = Color(0xFF2D3EB5)
val OnSecondaryContainerDark = Color(0xFFDEE0FF)
val TertiaryDark = Color(0xFF8DCDFF)
val OnTertiaryDark = Color(0xFF003350)
val TertiaryContainerDark = Color(0xFF004B70)
val OnTertiaryContainerDark = Color(0xFFCAE6FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val SurfaceDark = Color(0xFF111416)
val OnSurfaceDark = Color(0xFFE1E2E8)
val SurfaceVariantDark = Color(0xFF444750)
val OnSurfaceVariantDark = Color(0xFFC4C6D0)
val SurfaceDimDark = Color(0xFF111416)
val SurfaceBrightDark = Color(0xFF37393E)
val SurfaceContainerLowestDark = Color(0xFF0B0E11)
val SurfaceContainerLowDark = Color(0xFF191C1F)
val SurfaceContainerDark = Color(0xFF1D2024)
val SurfaceContainerHighDark = Color(0xFF282A2F)
val SurfaceContainerHighestDark = Color(0xFF33353A)
val OutlineDark = Color(0xFF8E9099)
val OutlineVariantDark = Color(0xFF444750)
val InverseSurfaceDark = Color(0xFFE1E2E8)
val InverseOnSurfaceDark = Color(0xFF2E3132)
val InversePrimaryDark = Color(0xFF0056C5)
val BackgroundDark = Color(0xFF111416)
val OnBackgroundDark = Color(0xFFE1E2E8)

// ---- 语义扩展色（状态监控页用，设计稿 emerald/amber 系）----
val StatusSuccess = Color(0xFF10B981)
val StatusSuccessContainer = Color(0xFFD1FAE5)
val OnStatusSuccessContainer = Color(0xFF002106)
val StatusWarning = Color(0xFFF59E0B)
val StatusWarningContainer = Color(0xFFFEF3C7)
val OnStatusWarningContainer = Color(0xFF2C1600)
