package com.easytier.android.ui.theme

import androidx.compose.ui.graphics.Color

// ---- 浅色（"Calm Mesh" 色板：靛蓝主色 + 冷调中性面）----
val Primary = Color(0xFF2F55D6)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFDEE4FF)
val OnPrimaryContainer = Color(0xFF0B2278)
val Secondary = Color(0xFF3F53C9)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE0E5FF)
val OnSecondaryContainer = Color(0xFF0F1B6E)
// 青绿：上行/tx 专用语义
val Tertiary = Color(0xFF00695F)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF9FF2E2)
val OnTertiaryContainer = Color(0xFF00201B)
// Error 系保持 MD3 默认
val ErrorC = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
val Surface = Color(0xFFFAFAFC)
val OnSurface = Color(0xFF191B23)
val SurfaceVariant = Color(0xFFE2E4EE)
val OnSurfaceVariant = Color(0xFF44485A)
val SurfaceDim = Color(0xFFDADBE3)
val SurfaceBright = Color(0xFFFAFAFC)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF4F5F9)
val SurfaceContainer = Color(0xFFEEF0F6)
val SurfaceContainerHigh = Color(0xFFE8EAF1)
val SurfaceContainerHighest = Color(0xFFE2E4ED)
val Outline = Color(0xFF757A8C)
val OutlineVariant = Color(0xFFC5C9DA)
val InverseSurface = Color(0xFF2E3038)
val InverseOnSurface = Color(0xFFF0F0F6)
val InversePrimary = Color(0xFFB9C4FF)
val Background = Color(0xFFFAFAFC)
val OnBackground = Color(0xFF191B23)

// ---- Fixed 色（沿用现值结构，微调对齐新 primary 色相）----
val PrimaryFixed = Color(0xFFDEE4FF)
val PrimaryFixedDim = Color(0xFFB9C4FF)
val OnPrimaryFixed = Color(0xFF001052)
val OnPrimaryFixedVariant = Color(0xFF2946BD)
val SecondaryFixed = Color(0xFFE0E5FF)
val SecondaryFixedDim = Color(0xFFBAC3FF)
val OnSecondaryFixed = Color(0xFF000F5C)
val OnSecondaryFixedVariant = Color(0xFF333D9E)
// Tertiary 改青绿后 fixed 色同步换到 emerald 色相
val TertiaryFixed = Color(0xFF9FF2E2)
val TertiaryFixedDim = Color(0xFF80D9C7)
val OnTertiaryFixed = Color(0xFF00201B)
val OnTertiaryFixedVariant = Color(0xFF005043)

// ---- 深色（冷调炭黑带蓝底韵，MD3 规则从 fixed 色派生）----
val PrimaryDark = Color(0xFFB7C3FF)
val OnPrimaryDark = Color(0xFF132A78)
val PrimaryContainerDark = Color(0xFF2946BD)
val OnPrimaryContainerDark = Color(0xFFDEE4FF)
val SecondaryDark = Color(0xFFBFC6FF)
val OnSecondaryDark = Color(0xFF16246F)
val SecondaryContainerDark = Color(0xFF333D9E)
val OnSecondaryContainerDark = Color(0xFFE1E5FF)
val TertiaryDark = Color(0xFF80D9C7)
val OnTertiaryDark = Color(0xFF00382F)
val TertiaryContainerDark = Color(0xFF005043)
val OnTertiaryContainerDark = Color(0xFF9FF2E2)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val SurfaceDark = Color(0xFF101218)
val OnSurfaceDark = Color(0xFFE3E5EC)
val SurfaceVariantDark = Color(0xFF42465A)
val OnSurfaceVariantDark = Color(0xFFC4C8D9)
val SurfaceDimDark = Color(0xFF101218)
val SurfaceBrightDark = Color(0xFF383B47)
// Lowest 故意抬亮：供卡片默认底色两态通用
val SurfaceContainerLowestDark = Color(0xFF15181F)
val SurfaceContainerLowDark = Color(0xFF171A22)
val SurfaceContainerDark = Color(0xFF1B1E27)
val SurfaceContainerHighDark = Color(0xFF262A35)
val SurfaceContainerHighestDark = Color(0xFF313542)
val OutlineDark = Color(0xFF8D92A8)
val OutlineVariantDark = Color(0xFF3E4356)
val InverseSurfaceDark = Color(0xFFE3E5EC)
val InverseOnSurfaceDark = Color(0xFF2E3038)
val InversePrimaryDark = Color(0xFF2F55D6)
val BackgroundDark = Color(0xFF101218)
val OnBackgroundDark = Color(0xFFE3E5EC)

// ---- 语义扩展色（状态监控页用，emerald/amber 系，色相保留微调和谐）----
val StatusSuccess = Color(0xFF10B981)
val StatusSuccessContainer = Color(0xFFD1FAE5)
val OnStatusSuccessContainer = Color(0xFF002106)
val StatusWarning = Color(0xFFF59E0B)
val StatusWarningContainer = Color(0xFFFEF3C7)
val OnStatusWarningContainer = Color(0xFF2C1600)

// ---- 语义扩展色深色变体（emerald/amber 深色系，按 MD3 深色容器规则取深底浅字）----
val StatusSuccessDark = Color(0xFF6EE7B7)
val StatusSuccessContainerDark = Color(0xFF064E3B)
val OnStatusSuccessContainerDark = Color(0xFFA7F3D0)
val StatusWarningDark = Color(0xFFFBBF24)
val StatusWarningContainerDark = Color(0xFF422006)
val OnStatusWarningContainerDark = Color(0xFFFDE68A)
