package com.easytier.android.core.toml

import com.easytier.android.data.model.NetworkConfig
import com.easytier.android.data.model.NetworkingMethod
import com.easytier.android.data.model.PortForwardEntry
import java.util.UUID

/**
 * NetworkConfig -> EasyTier TOML 生成器。
 *
 * 镜像 easytier-core/src/config/api_input.rs 的 gen_config()：
 * - instance_name = networkName
 * - [network_identity] network_name/network_secret
 * - PublicServer: peers = [public_server_url]；Manual: peers = peer_urls
 * - dhcp=false 时写 ipv4 = "x.x.x.x/len"
 * - 高级开关仅在与核心默认值不同时写入 [flags]
 */
object TomlGenerator {

    /** 核心默认 flags（easytier-core/src/config/toml.rs gen_default_flags）。 */
    private val DEFAULT_FLAGS: Map<String, Any> = mapOf(
        "default_protocol" to "tcp",
        "enable_encryption" to true,
        "enable_ipv6" to true,
        "mtu" to 1380,
        "latency_first" to false,
        "enable_exit_node" to false,
        "proxy_forward_by_system" to false,
        "no_tun" to false,
        "use_smoltcp" to false,
        "relay_network_whitelist" to "*",
        "disable_p2p" to false,
        "p2p_only" to false,
        "lazy_p2p" to false,
        "relay_all_peer_rpc" to false,
        "disable_tcp_hole_punching" to false,
        "disable_udp_hole_punching" to false,
        "multi_thread" to true,
        "bind_device" to true,
        "enable_kcp_proxy" to false,
        "disable_kcp_input" to false,
        "enable_quic_proxy" to false,
        "disable_quic_input" to false,
        "disable_sym_hole_punching" to false,
        "disable_upnp" to false,
        "disable_relay_data" to false,
        "enable_udp_broadcast_relay" to false,
        "need_p2p" to false,
    )

    /**
     * 生成 EasyTier TOML。
     *
     * @param includeInstanceId 引擎启动时必须为 true（身份需稳定持久）；
     *   导出/分享时传 false：核心侧 instance_id 是 Option（toml.rs），缺失时自动生成，
     *   带上本机身份会让导入方与我们同 peer_id 互踢。
     */
    fun generate(config: NetworkConfig, includeInstanceId: Boolean = true): String {
        val sb = StringBuilder()

        sb.appendLine("# EasyTier config (generated by EasyTier Android)")
        sb.appendLine("instance_name = \"${escape(config.networkName)}\"")
        if (includeInstanceId) {
            val instanceId = config.instanceId ?: UUID.randomUUID().toString()
            sb.appendLine("instance_id = \"$instanceId\"")
        }
        config.hostname?.takeIf { it.isNotBlank() }?.let { sb.appendLine("hostname = \"${escape(it)}\"") }
        sb.appendLine("dhcp = ${config.dhcp}")

        if (!config.dhcp) {
            config.virtualIpv4?.takeIf { it.isNotBlank() }?.let { ip ->
                sb.appendLine("ipv4 = \"$ip/${config.networkLength}\"")
            }
        }

        // listeners：顶层键，必须写在任何 [table] 头之前（TOML 语义）。
        // 空时用官方客户端同款默认值（frontend-lib types/network.ts）：
        // 无 UDP 监听时 NAT 映射过期后重打洞成功率差，直连会永久退化成中转。
        val listeners = config.listenerUrls.filter { it.isNotBlank() }
            .ifEmpty { listOf("tcp://0.0.0.0:11010", "udp://0.0.0.0:11010", "wg://0.0.0.0:11011") }
        sb.appendLine("listeners = [${listeners.joinToString(", ") { "\"${escape(it)}\"" }}]")

        // SOCKS5：核心 TOML 结构（toml.rs Config）中的顶层键是 socks5_proxy URL，
        // 不是 [flags]；必须在任何 [table] 头之前写出。
        if (config.enableSocks5 == true) {
            val port = config.socks5Port ?: 1080
            sb.appendLine("socks5_proxy = \"socks5://0.0.0.0:$port\"")
        }

        // 出口节点：同样是核心 Config 的顶层键（Vec<IpAddr>）
        val exitNodes = config.exitNodes.orEmpty().filter { it.isNotBlank() }
        if (exitNodes.isNotEmpty()) {
            sb.appendLine(
                "exit_nodes = [${exitNodes.joinToString(", ") { "\"${escape(it)}\"" }}]",
            )
        }

        sb.appendLine()
        sb.appendLine("[network_identity]")
        sb.appendLine("network_name = \"${escape(config.networkName)}\"")
        config.networkSecret?.let { sb.appendLine("network_secret = \"${escape(it)}\"") }

        // peers
        val peers: List<String> = when (config.networkingMethod) {
            NetworkingMethod.PublicServer ->
                listOfNotNull(config.publicServerUrl?.takeIf { it.isNotBlank() })
            NetworkingMethod.Manual -> config.peerUrls.filter { it.isNotBlank() }
            NetworkingMethod.Standalone -> emptyList()
        }
        if (peers.isNotEmpty()) {
            sb.appendLine()
            peers.forEach { sb.appendLine("[[peer]]\nuri = \"${escape(it)}\"") }
        }

        // proxy networks
        if (config.proxyCidrs.isNotEmpty()) {
            sb.appendLine()
            config.proxyCidrs.forEach { entry ->
                val parts = entry.split("->")
                val cidr = parts[0].trim()
                val mapped = parts.getOrNull(1)?.trim()
                if (mapped != null) {
                    sb.appendLine("[[proxy_network]]\ncidr = \"$cidr\"\nmapped_cidr = \"$mapped\"")
                } else {
                    sb.appendLine("[[proxy_network]]\ncidr = \"$cidr\"")
                }
            }
        }

        // port forwards
        if (config.portForwards.isNotEmpty()) {
            sb.appendLine()
            config.portForwards
                .filter { it.bindIp.isNotBlank() && it.dstIp.isNotBlank() }
                .forEach { pf ->
                    sb.appendLine(
                        "[[port_forward]]\nbind_addr = \"${pf.bindIp}:${pf.bindPort}\"\ndst_addr = \"${pf.dstIp}:${pf.dstPort}\"\nproto = \"${pf.proto}\"",
                    )
                }
        }

        // VPN portal
        if (config.enableVpnPortal) {
            sb.appendLine()
            sb.appendLine("[vpn_portal_config]")
            sb.appendLine("client_cidr = \"${config.vpnPortalClientNetworkAddr}/${config.vpnPortalClientNetworkLen}\"")
            sb.appendLine("wireguard_listen = \"0.0.0.0:${config.vpnPortalListenPort}\"")
        }

        // flags（仅写非默认值）
        val flags = LinkedHashMap<String, Any>()
        config.latencyFirst?.let { flags["latency_first"] = it }
        config.useSmoltcp?.let { flags["use_smoltcp"] = it }
        config.enableKcpProxy?.let { flags["enable_kcp_proxy"] = it }
        config.disableKcpInput?.let { flags["disable_kcp_input"] = it }
        config.disableP2p?.let { flags["disable_p2p"] = it }
        config.bindDevice?.let { flags["bind_device"] = it }
        config.noTun?.let { flags["no_tun"] = it }
        config.enableExitNode?.let { flags["enable_exit_node"] = it }
        config.relayAllPeerRpc?.let { flags["relay_all_peer_rpc"] = it }
        config.multiThread?.let { flags["multi_thread"] = it }
        config.proxyForwardBySystem?.let { flags["proxy_forward_by_system"] = it }
        config.disableEncryption?.let { flags["enable_encryption"] = !it }
        config.disableUdpHolePunching?.let { flags["disable_udp_hole_punching"] = it }
        config.disableTcpHolePunching?.let { flags["disable_tcp_hole_punching"] = it }
        config.disableSymHolePunching?.let { flags["disable_sym_hole_punching"] = it }
        config.mtu?.let { flags["mtu"] = it }
        config.p2pOnly?.let { flags["p2p_only"] = it }
        config.lazyP2p?.let { flags["lazy_p2p"] = it }
        config.needP2p?.let { flags["need_p2p"] = it }
        config.disableUpnp?.let { flags["disable_upnp"] = it }
        config.disableRelayData?.let { flags["disable_relay_data"] = it }
        config.enableUdpBroadcastRelay?.let { flags["enable_udp_broadcast_relay"] = it }
        config.disableIpv6?.let { flags["enable_ipv6"] = !it }
        config.dataCompressAlgo?.let { flags["data_compress_algo"] = it }
        config.encryptionAlgorithm?.let { flags["encryption_algorithm"] = it }
        config.devName?.takeIf { it.isNotBlank() }?.let { flags["dev_name"] = it }
        config.instanceRecvBpsLimit?.let { flags["instance_recv_bps_limit"] = it.toString() }
        config.relayNetworkWhitelist?.takeIf { it.isNotEmpty() }?.let {
            flags["relay_network_whitelist"] = it.joinToString(",")
        }

        if (flags.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("[flags]")
            flags.forEach { (k, v) -> sb.appendLine("$k = ${formatValue(v)}") }
        }

        // ACL 内联片段
        config.acl?.takeIf { it.isNotBlank() }?.let { sb.appendLine().appendLine(it) }

        return sb.toString().trimEnd('\n') + "\n"
    }

    /** 仅输出与默认值不同的 flags（用于差异展示）。 */
    fun diffFromDefaults(config: NetworkConfig): Map<String, Pair<Any, Any>> = buildMap {
        config.latencyFirst?.let { put("latency_first", DEFAULT_FLAGS["latency_first"]!! to it) }
        config.useSmoltcp?.let { put("use_smoltcp", DEFAULT_FLAGS["use_smoltcp"]!! to it) }
        config.enableKcpProxy?.let { put("enable_kcp_proxy", DEFAULT_FLAGS["enable_kcp_proxy"]!! to it) }
        config.disableKcpInput?.let { put("disable_kcp_input", DEFAULT_FLAGS["disable_kcp_input"]!! to it) }
        config.disableP2p?.let { put("disable_p2p", DEFAULT_FLAGS["disable_p2p"]!! to it) }
        config.bindDevice?.let { put("bind_device", DEFAULT_FLAGS["bind_device"]!! to it) }
        config.noTun?.let { put("no_tun", DEFAULT_FLAGS["no_tun"]!! to it) }
        config.enableExitNode?.let { put("enable_exit_node", DEFAULT_FLAGS["enable_exit_node"]!! to it) }
        config.relayAllPeerRpc?.let { put("relay_all_peer_rpc", DEFAULT_FLAGS["relay_all_peer_rpc"]!! to it) }
        config.multiThread?.let { put("multi_thread", DEFAULT_FLAGS["multi_thread"]!! to it) }
        config.proxyForwardBySystem?.let { put("proxy_forward_by_system", DEFAULT_FLAGS["proxy_forward_by_system"]!! to it) }
        config.disableEncryption?.let { put("enable_encryption", true to !it) }
        config.disableUdpHolePunching?.let { put("disable_udp_hole_punching", DEFAULT_FLAGS["disable_udp_hole_punching"]!! to it) }
        config.disableTcpHolePunching?.let { put("disable_tcp_hole_punching", DEFAULT_FLAGS["disable_tcp_hole_punching"]!! to it) }
        config.disableSymHolePunching?.let { put("disable_sym_hole_punching", DEFAULT_FLAGS["disable_sym_hole_punching"]!! to it) }
        config.mtu?.let { put("mtu", DEFAULT_FLAGS["mtu"]!! to it) }
        config.p2pOnly?.let { put("p2p_only", DEFAULT_FLAGS["p2p_only"]!! to it) }
        config.lazyP2p?.let { put("lazy_p2p", DEFAULT_FLAGS["lazy_p2p"]!! to it) }
        config.needP2p?.let { put("need_p2p", DEFAULT_FLAGS["need_p2p"]!! to it) }
        config.disableUpnp?.let { put("disable_upnp", DEFAULT_FLAGS["disable_upnp"]!! to it) }
        config.disableRelayData?.let { put("disable_relay_data", DEFAULT_FLAGS["disable_relay_data"]!! to it) }
        config.enableUdpBroadcastRelay?.let { put("enable_udp_broadcast_relay", DEFAULT_FLAGS["enable_udp_broadcast_relay"]!! to it) }
        config.disableIpv6?.let { put("enable_ipv6", true to !it) }
        config.enableSocks5?.let { put("enable_socks5", false to it) }
    }

    private fun formatValue(v: Any): String = when (v) {
        is String -> "\"${escape(v)}\""
        is Boolean -> v.toString()
        is Int, is Long -> v.toString()
        else -> "\"$v\""
    }

    private fun escape(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
}
